### PR TITLE
Add support for Deneb EIP-4844 types (blobs support)

### PR DESCRIPTION
**Pull request by jimmygchen**
Builder spec: https://github.com/ethereum/builder-specs/pull/61

This PR updates the Deneb EIP-4844 types only, logic for supporting blobs are not implemented.

### CODE REVIEW

**Comment by jimmygchen** [comment]
Hey @ralexstokes 👋 
I think this PR is ready for a round of review when you have some time, thanks!

**Review by ralexstokes — COMMENTED** [review]
thanks for this @jimmygchen !

it may need one more rebase from `main` but I think it is good enough to merge for now

**Comment by jimmygchen** [comment]
Thanks @ralexstokes I'm seeing a test failure locally, looking into it now

**Comment by jimmygchen** [comment]
Turned out it was a local issue, CI is passing locally now!

**Pull request merged**
